### ISSUE TITLE
Adding datatypes [money]

### ISSUE THREAD

**Issue by securekomodo** [gsiems/bac-tract#1]
Looks like the smallmoney datatype is supported however money is not.

I believe the only difference is smallmoney is INT and money is BigINT - 8bytes

**Comment by securekomodo** [comment]
For now you can replace the money datatype in the model.xml into bigint which allows the script to complete

**Comment by gsiems** [comment]
I've added the money data-type (apologies for taking so long to get to this). Please let me know if there are issues with the update.

**Comment by gsiems** [comment]
fixed
